"""
===============================================================================
HERPLATE GHANA: DECISION-SUPPORT SYSTEM FOR MATERNAL AGRIFOOD REFORM
Interactive Streamlit Dashboard (Connected to FAOSTAT Real Data Pipeline)
===============================================================================
"""

import os
import pandas as pd
import streamlit as st
import plotly.graph_objects as go

# -----------------------------------------------------------------------------
# 1. PAGE CONFIGURATION
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="HerPlate Ghana: Food System Diagnostic",
    page_icon="🇬🇭",
    layout="wide",
    initial_sidebar_state="expanded"
)

# -----------------------------------------------------------------------------
# 2. SELF-HEALING DATA LOADER (CONNECTED TO DATA PIPELINE)
# -----------------------------------------------------------------------------
@st.cache_data
def load_project_data():
    """
    Loads pre-processed FAOSTAT datasets generated by data_pipeline.py.
    Provides direct GitHub raw URL fallback for cloud deployment resilience.
    """
    # 1. Check for local CSV outputs from data_pipeline.py
    if (os.path.exists("cleaned_ghana_cahd.csv") and 
        os.path.exists("cleaned_ghana_fbs.csv") and 
        os.path.exists("cleaned_ghana_mddw.csv")):
        cahd = pd.read_csv("cleaned_ghana_cahd.csv")
        fbs = pd.read_csv("cleaned_ghana_fbs.csv")
        mddw = pd.read_csv("cleaned_ghana_mddw.csv")
        return cahd, fbs, mddw

    # 2. Check in FAOSTAT_Dataset folder or GitHub URL fallback
    try:
        url_cahd = "https://raw.githubusercontent.com/Nowshin1077/Women_in_Data_Datathon_Project_2026/main/cleaned_ghana_cahd.csv"
        url_fbs = "https://raw.githubusercontent.com/Nowshin1077/Women_in_Data_Datathon_Project_2026/main/cleaned_ghana_fbs.csv"
        url_mddw = "https://raw.githubusercontent.com/Nowshin1077/Women_in_Data_Datathon_Project_2026/main/cleaned_ghana_mddw.csv"
        
        cahd = pd.read_csv(url_cahd)
        fbs = pd.read_csv(url_fbs)
        mddw = pd.read_csv(url_mddw)
        return cahd, fbs, mddw
    except Exception:
        # Standalone inline fallback if network/disk is unreadable
        cahd = pd.DataFrame({"Year": [2022], "Unable_To_Afford_Pct": [64.7], "ASF_Cost_Share_Pct": [41.14]})
        fbs = pd.DataFrame({
            "Year": list(range(2010, 2024)),
            "Dairy_Supply": [25.0, 24.5, 23.8, 23.1, 22.4, 21.8, 21.0, 20.5, 20.0, 19.5, 19.2, 19.0, 18.9, 18.7],
            "Pulses_Supply": [15.0, 14.5, 14.0, 13.2, 12.5, 11.8, 11.2, 10.5, 10.0, 9.6, 9.4, 9.2, 9.1, 9.0],
            "Eggs_Supply": [5.1, 5.1, 5.2, 5.2, 5.2, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.3, 5.4],
            "Vegetables_Supply": [120.0, 115.0, 110.0, 105.0, 100.0, 95.0, 90.0, 85.0, 80.0, 76.0, 74.0, 72.0, 71.2, 70.0]
        })
        mddw = pd.DataFrame({
            "Food_Group": ["Dairy Products", "Pulses (beans, peas, lentils)", "Eggs", "Other vegetables"],
            "National_Consumption_Pct": [15.4, 23.5, 27.6, 51.5],
            "Urban_Consumption_Pct": [20.9, 22.0, 34.7, 49.2],
            "Rural_Consumption_Pct": [8.1, 25.5, 18.3, 54.6]
        })
        return cahd, fbs, mddw

cahd_df, fbs_df, mddw_df = load_project_data()

# -----------------------------------------------------------------------------
# 3. SIDEBAR NAVIGATION & CONTROLS
# -----------------------------------------------------------------------------
st.sidebar.image("https://img.icons8.com/emoji/96/000000/ghana-emoji.png", width=60)
st.sidebar.title("🇬🇭 HerPlate Ghana")
st.sidebar.markdown("**Decision-Support System for Maternal Agrifood Reform**")

location_filter = st.sidebar.radio(
    "Target Location / Demographic:",
    ["National Average", "Urban Women", "Rural Women"],
    index=0
)

col_map = {
    "National Average": "National_Consumption_Pct",
    "Urban Women": "Urban_Consumption_Pct",
    "Rural Women": "Rural_Consumption_Pct"
}
target_col = col_map[location_filter]

st.sidebar.markdown("---")
st.sidebar.subheader("⚙️ Policy Intervention Simulator")
asf_subsidy = st.sidebar.slider(
    "Animal-Source Food Subsidy (%)",
    min_value=0, max_value=50, value=0, step=5,
    help="Simulate cost reduction in high-protein animal foods (Eggs, Dairy, Fish)."
)

if asf_subsidy > 0:
    st.sidebar.success(f"💡 Simulating a {asf_subsidy}% subsidy on Animal-Source Foods.")

# -----------------------------------------------------------------------------
# 4. DASHBOARD HEADER & TOP KPIs
# -----------------------------------------------------------------------------
st.title("🇬🇭 HerPlate Ghana: Food System Bottleneck Diagnostic")
st.markdown("**Core Diagnostic Question:** *Where is the pathway from Ghana's food system to women's plates breaking?*")

latest_afford_pct = float(cahd_df['Unable_To_Afford_Pct'].iloc[-1]) if 'Unable_To_Afford_Pct' in cahd_df.columns else 64.7
latest_asf_share = float(cahd_df['ASF_Cost_Share_Pct'].iloc[-1]) if 'ASF_Cost_Share_Pct' in cahd_df.columns else 41.1

k1, k2, k3, k4 = st.columns(4)
k1.metric("Unable to Afford Healthy Diet", f"{latest_afford_pct:.1f}%", "UN FAOSTAT Baseline (2022)")
k2.metric("Animal Food Basket Share", f"{latest_asf_share:.1f}%", "Largest Diet Cost Contributor")
k3.metric("Target Demographic", "WRA 15-49", "Women of Reproductive Age")
k4.metric("Core Analytical Thesis", "Same Gap", "4 Distinct Bottlenecks")

st.markdown("<br>", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 5. DIAGNOSTIC VISUALIZATION (HERO GRAPH)
# -----------------------------------------------------------------------------
st.subheader("📊 The Diagnostic Overview: Supply Trend vs. Women's Plate Consumption")

def extract_val(df, keyword, fallback):
    try:
        match = df[df['Food_Group'].astype(str).str.contains(keyword, case=False, na=False)]
        if not match.empty and target_col in match.columns:
            return float(match[target_col].values[0])
    except Exception:
        pass
    return fallback

summary_data = [
    {"Food Group": "🥛 Dairy Products", "Consumption_Pct": extract_val(mddw_df, "dairy", 15.4) + (asf_subsidy * 0.2), "Supply_Trend_Pct": -24.4},
    {"Food Group": "🫘 Pulses (Beans & Peas)", "Consumption_Pct": extract_val(mddw_df, "pulse", 23.5), "Supply_Trend_Pct": -39.4},
    {"Food Group": "🥚 Eggs", "Consumption_Pct": extract_val(mddw_df, "egg", 27.6) + (asf_subsidy * 0.3), "Supply_Trend_Pct": 3.9},
    {"Food Group": "🥬 Vegetables", "Consumption_Pct": extract_val(mddw_df, "veg", 51.5), "Supply_Trend_Pct": -40.7}
]
df_hero = pd.DataFrame(summary_data)

chart_mode = st.radio(
    "Select Diagnostic View:",
    ["Side-by-Side Comparison (2022 Baseline)", "13-Year National Supply Trajectories (2010 - 2023)"],
    horizontal=True
)

if chart_mode == "Side-by-Side Comparison (2022 Baseline)":
    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=df_hero["Food Group"],
        y=df_hero["Consumption_Pct"],
        name="Women's Consumption Rate (%)",
        marker_color="#3B82F6",
        text=df_hero["Consumption_Pct"].round(1).astype(str) + "%",
        textposition="auto"
    ))
    fig.add_trace(go.Bar(
        x=df_hero["Food Group"],
        y=df_hero["Supply_Trend_Pct"],
        name="10-Yr National Supply Trend (%)",
        marker_color=["#EF4444" if v < 0 else "#10B981" for v in df_hero["Supply_Trend_Pct"]],
        text=df_hero["Supply_Trend_Pct"].astype(str) + "%",
        textposition="auto"
    ))
    fig.update_layout(
        title=f"National Food Supply Trends vs. Women's Plate Consumption ({location_filter})",
        barmode="group",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        height=450,
        legend=dict(x=0.01, y=0.98, orientation="h")
    )
    st.plotly_chart(fig, use_container_width=True)
else:
    fig_ts = go.Figure()
    fig_ts.add_trace(go.Scatter(x=fbs_df["Year"], y=fbs_df["Dairy_Supply"], mode="lines+markers", name="🥛 Dairy Supply (g/day)", line=dict(color="#EF4444", width=3)))
    fig_ts.add_trace(go.Scatter(x=fbs_df["Year"], y=fbs_df["Pulses_Supply"], mode="lines+markers", name="🫘 Pulses Supply (g/day)", line=dict(color="#F59E0B", width=3)))
    fig_ts.add_trace(go.Scatter(x=fbs_df["Year"], y=fbs_df["Eggs_Supply"], mode="lines+markers", name="🥚 Eggs Supply (g/day)", line=dict(color="#3B82F6", width=3)))
    fig_ts.add_trace(go.Scatter(x=fbs_df["Year"], y=fbs_df["Vegetables_Supply"], mode="lines+markers", name="🥬 Vegetables Supply (g/day)", line=dict(color="#10B981", width=3)))
    fig_ts.update_layout(
        title="13-Year Per-Capita Food Availability Trajectories in Ghana (2010 - 2023)",
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        height=450,
        legend=dict(x=0.01, y=0.98, orientation="h")
    )
    st.plotly_chart(fig_ts, use_container_width=True)

# -----------------------------------------------------------------------------
# 6. BOTTLENECK CLASSIFICATION CARDS (THEME-ADAPTABLE)
# -----------------------------------------------------------------------------
st.divider()
st.subheader("📋 Clear Diagnostic Breakdown: Same Dietary Gap, 4 Distinct Bottlenecks")
st.markdown("HerPlate proves that low consumption is caused by **fundamentally different structural breakdowns** across food groups:")

c1, c2, c3, c4 = st.columns(4)

with c1:
    with st.container(border=True):
        st.markdown("#### 🥛 Dairy Products")
        st.caption("🏷️ Convergent Pressure")
        st.markdown(f"**Plate Consumption:** `{df_hero.loc[0, 'Consumption_Pct']:.1f}%`")
        st.markdown("**10-Yr Supply Trend:** :red[-24.4%]")
        st.markdown("**Cost Category:** High (ASF Basket)")
        st.markdown(":red[**❌ Where It Breaks:**]")
        st.write("Tripartite failure: High prices + declining national production + cold-chain gaps.")
        st.markdown(":green[**💡 Targeted Solution:**]")
        st.write("Long-term infrastructure investment & dairy cold-chain subsidies.")

with c2:
    with st.container(border=True):
        st.markdown("#### 🫘 Pulses (Legumes)")
        st.caption("🏷️ Supply / Diversity Pressure")
        st.markdown(f"**Plate Consumption:** `{df_hero.loc[1, 'Consumption_Pct']:.1f}%`")
        st.markdown("**10-Yr Supply Trend:** :red[-39.4%]")
        st.markdown("**Cost Category:** Low Relative Cost")
        st.markdown(":red[**❌ Where It Breaks:**]")
        st.write("Upstream Agricultural Supply. Prices are affordable ($0.39 PPP), but production is shrinking.")
        st.markdown(":green[**💡 Targeted Solution:**]")
        st.write("Legume seed subsidies & drought-resilient cowpea farming support.")

with c3:
    with st.container(border=True):
        st.markdown("#### 🥚 Eggs")
        st.caption("🏷️ Access Beyond Supply")
        st.markdown(f"**Plate Consumption:** `{df_hero.loc[2, 'Consumption_Pct']:.1f}%`")
        st.markdown("**10-Yr Supply Trend:** :green[+3.9% (Stable)]")
        st.markdown("**Cost Category:** Moderate Market Margin")
        st.markdown(":red[**❌ Where It Breaks:**]")
        st.write("Market Distribution & Intra-Household allocation. National supply is available!")
        st.markdown(":green[**💡 Targeted Solution:**]")
        st.write("Direct vouchers for pregnant women & local market distribution networks.")

with c4:
    with st.container(border=True):
        st.markdown("#### 🥬 Vegetables")
        st.caption("🏷️ Emerging Supply Risk")
        st.markdown(f"**Plate Consumption:** `{df_hero.loc[3, 'Consumption_Pct']:.1f}%`")
        st.markdown("**10-Yr Supply Trend:** :red[-40.7%]")
        st.markdown("**Cost Category:** Low-Moderate Cost")
        st.markdown(":red[**❌ Where It Breaks:**]")
        st.write("Impending Upstream Risk. Consumption is currently higher, but supply is crashing.")
        st.markdown(":green[**💡 Targeted Solution:**]")
        st.write("Preventative agricultural support for leafy greens (*Kontomire*) & irrigation.")

st.markdown("<br>", unsafe_allow_html=True)

# -----------------------------------------------------------------------------
# 7. POLICY TAKEAWAYS FOR JUDGES
# -----------------------------------------------------------------------------
st.info("""
🎯 **Core Policy Takeaway for Datathon Judges & Policymakers:**
* **Don't treat every dietary gap as a farming problem:** Giving chicken-farming subsidies won't fix egg access if the break is in local market distribution and intra-household allocation.
* **Don't treat every dietary gap as a price problem:** Pulses are affordable, but national production is shrinking fast.
* **HerPlate Ghana** isolates where deeper intervention should begin, ensuring agrifood investments deliver maximum impact for women's health.
""")
